### ISSUE TITLE
Añadir documentación fácil y bonita

### ISSUE THREAD

**Issue by miguelpaz** [datal-org/datal#54]
A prueba de gente como uno.

**Comment by javierpajaro** [comment]
@miguelpaz hay algo hecho, pero falta. Te sumas?

**Comment by miguelpaz** [comment]
por estos días cobro por trabajar, incluso en open source ;) 
más adelante cuando tenga tiempo encantado pero tendría que poder ver el demo al menos

**Comment by dbleyenda** [comment]
@miguelpaz Aqui las instrucciones de instalacion del entorno local: https://github.com/datal-org/datal.

Cualquier duda avisa.

**Comment by javierpajaro** [comment]
@danielpadula te estara ayudando a ver el demo. Podes usarlo tambien en http://workspace.demo.junar.com/ y entrar como publicador/publicador

**Comment by miguelpaz** [comment]
Gracias

**Comment by danielpadula** [comment]
Te sirve la demo para probarlo ? Sino Consultame que te doy una mano!

**Comment by miguelpaz** [comment]
me sirve, gracias.
sugiero agregar ese demo online a la documentación para non coders


El 20 de noviembre de 2015, 19:56, Daniel Padula <notifications@github.com>
escribió:

> Te sirve la demo para probarlo ? Sino Consultame que te doy una mano!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datal-org/datal/issues/54#issuecomment-158550908>.
>



-- 
Miguel Paz @miguelpaz
Nieman-Berkman Fellow 2014-2015
Poderomedia.org @poderomedia - Poderopedia.org @poderopedia
PoderomediaAcademy #PAcademy - Manual Periodismo de Datos @periodismodata
Hacks/Hackers Chile @hackshackersSCL

**Comment by danielpadula** [comment]
Excelente Miguel!

Te cuento de paso que recién acabo de subir una nueva versión con muchas correcciones (Normalmente los viernes pasamos al sitio de demo los últimos cambios) así que cuando quieras podes probarlo.
Recordá el sitio es http://workspace.demo.junar.com 
Usuario: administrador
Contraseña: administrador

Muchas gracias!
