### ISSUE TITLE
URL de demo no abre 

### ISSUE THREAD

**Issue by miguelpaz** [datal-org/datal#55]
Página no disponible.

**Comment by javierpajaro** [comment]
@danielpadula por favor dale una mano a @miguelpaz para que pueda empezar.

**Comment by dbleyenda** [comment]
Hola @miguelpaz, ¿podrías indicar mas detalles? ¿A que URL de demo haces referencia?

**Comment by dbleyenda** [comment]
Si te refieres a la que de indica en el readme de la documentación de instalación (https://github.com/datal-org/datal), dicha url de un servidor local, el cual comienza a funcionar cuando instalas Datal en tu maquina.

**Comment by miguelpaz** [comment]
A ese me refiero. Entonces debe decir demo en local host

**Comment by danielpadula** [comment]
La url de demo es workspace.demo.junar.com y la de la instalación local es workspace.dev:8080

Si hiciste la instalación local por favor mostrame que te sucede y te guío

**Comment by miguelpaz** [comment]
No hice instalación. Sólo leí que decía: demo en url.... e hice click y nada. ¿Es obvio que ese demo es de localhost? En realidad no. ¿Razón? Porque soy un tipo de usuario no programador. Pero puedo ser uno que toma la decisión de compra. Y tener un link a un demo web para ese tipo de usuario es vital para su negocio.
Uno de los grandes desafíos de los proyectos open source en general y de open source con negocio comercial apalancado en específico es contar con MUY buena documentación (aprendido de la manera más difícil). Al respecto sugiero leer y aplicar en la medida de sus posibilidades estos "20 consejos para documentar código bien para que otros lo entiendan y usen" http://datamade.us/blog/better-living-through-documentation/

**Comment by danielpadula** [comment]
Gran consejo Miguel!
Uno, por mas que intente no hacerlo, ve solo desde nuestra perspectiva y no debe ser así, debe ser general.
Muchas gracias por el aporte!
